import Head from "next/head";
import { Typography } from "@aura-ui/react";
import { AppLayout } from "@/modules/Layout/AppLayout";

export default function Home() {
  return (
    // <>
    <AppLayout>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </Head> */}

      <Typography size="4" weight="6" contrast="hiContrast" css={{ mb: "$5" }}>
        Feed
      </Typography>
    </AppLayout>
    // </>
  );
}
