import Head from "next/head";
import { Box, Flex, Typography } from "@aura-ui/react";
import { ConnectWallet } from "@/modules/ConnectWallet";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      <Flex justify="between" css={{ py: "$5", px: "$20" }} as="header">
        <Typography
          css={{
            py: "$2",
            px: "$4",
            boxShadow: "0 0 0 1px $colors$slate12",
            br: "$3",
          }}
          contrast="hiContrast"
          size="4"
          weight="6"
        >
          sharespace_
        </Typography>
        <ConnectWallet permissions={["ACCESS_ADDRESS"]} />
      </Flex>
    </>
  );
}
